#define N 30
#include <stdio.h>
int main()  
{  
 	int n, x, count, i =0, j =0, k, m;  
 	int a[N][N] = {0};  
 	
	printf("Enter N: ");  
 	scanf("%d", &n);  

 	int original_n = n; // keep original n from being changed
 
 /* This program outputs a series of numbers arranged in a clockwise spiral pattern.  
	Each subsequent array reduces its size by2 (i.e., n is decremented by2).  
	Additionally, the values of the numbers in each spiral increase by a constant value.  
	The spiral pattern gradually moves towards the center, effectively shifting the indices by one to achieve this inward motion.  */
  	
	for(n = n, x = 0, count = 0; n >= 2; n -= 2, x ++, count += n+1)      														
		{
		for(j = 0; j < n - 1; j++)
			a[x][j+x] = j + 1 + 4 * count ;
		for(i = 0; i < n - 1; i++)
			a[i+x][n -1 + x] = n + i + 4 * count ;
		for(j = n - 1; j > 0 ; j--)	
			a[n - 1 + x][j + x] = 3 * n - 2 - j + 4 * count;
		for(i = n - 1; i > 0; i--)
			a[i + x][0 + x] = 4 * n - 3 - i + 4 * count ;
		}

	if (original_n % 2)
		a[original_n / 2][original_n / 2] = original_n * original_n;//because the square is generated by n-1 steps, we have ton specially judge the odd number 
 // output the 2-D spiral pattern
 	for (k =0; k < original_n; k++)  
 	{  
	 	for (m =0; m < original_n; m++)  
 			printf("%4d", a[k][m]);  
 		printf("\n");  
 	}  
 	
 	return 0;  
}
